### PR TITLE
Hide Handle Timer

### PR DESCRIPTION
**Pull request by tom5079**

### CODE REVIEW

**Comment by shahsurajk** [comment]
@tom5079 does this fix #20?

**Comment by tom5079** [comment]
No, that issue is for pre-delay. This is for post-delay.

**Comment by shahsurajk** [comment]
@tom5079 as a practice, let's use these guidelines for a pull request: https://github.com/mozilla-mobile/fenix/#i-want-to-open-a-pull-request.

**Comment by tom5079** [comment]
@shahsurajk PRs after #29 are temporary as they depend on each other which makes the commits look dirty.
I'll reopen the PR and create new issue once #29 is merged.

**Comment by tom5079** [comment]
I'll just open another PR. This one is too messy with merge commits

**Pull request closed without merging**
