### PR TITLE
Hide Popup when OnPopupViewUpdate is not implemented

### LINKED ISSUE #27: java.lang.IllegalAccessException: Should implement the OnPopupTextUpdate or OnPopupViewUpdate interface
Why does it raise an exception?
Just not showing the popup when it's not implemented makes much more sense

### PR DESCRIPTION
**Pull request by tom5079**
resolves #27

### CODE REVIEW

**Review by shahsurajk — APPROVED** [review]

**Review by shahsurajk — CHANGES_REQUESTED** [review]
should update the documentation for the method here: 
https://github.com/quiph/RecyclerView-FastScroller/blob/0535c439967396641a7d99b58f4c6fe82e267e44/recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt#L626

**Comment by tom5079** [comment]
@shahsurajk Do we even need documentation there? I think the function name is self-explanatory.

**Comment by shahsurajk** [comment]
> @shahsurajk Do we even need documentation there? I think the function name is self-explanatory.

The current documentation is very ambiguous. It should be update to mention the the popup text will hide if a listener is not implemented

**Comment by tom5079** [comment]
@shahsurajk ok

**Pull request merged**
